# Site
name: "Design In Singapore"
title: "Design In Singapore"
description: "Your Creative Escape"
logo: 'assets/images/DIS-wordmark-blue.png'
favicon: 'assets/images/favicon-32x32.png'
baseurl: /sg
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'https://dis-sg.github.io/sg/'
mailchimp-list: false
include: ["_pages"]
permalink: /:title/
email: designinsingapore65@gmail.com

# Authors
authors:
  d:
    name: Darryl
    display_name: Darryl
    gravatar: 'assets/images/avatar.png'
    email: designinsingapore65@gmail.com
    web: 'https://dis-sg.github.io/sg/about'
    twitter: false
    description: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
